---
- name: Install Coco
  unarchive:
    src: '{{ jumpserver_soft_url }}/coco/archive/{{ jumpserver_version }}.tar.gz'
    dest: '{{ jumpserver_path }}'
    remote_src: 'yes'
    validate_certs: 'no'
  register: coco_update
  until: coco_update is succeeded
  retries: 3
  delay: 5

- name: Install Coco dependence python package
  pip:
    requirements: '{{ jumpserver_path }}/coco-{{ jumpserver_version }}/requirements/requirements.txt'
    state: 'present'
    virtualenv_command: '/bin/virtualenv-3'
    virtualenv_python: '/bin/python3'
    virtualenv: '{{ jumpserver_env }}'
    extra_args: '-i {{ jumpserver_pypi_url }}'
  register: coco_dependence_update
  until: coco_dependence_update is succeeded
  retries: 3
  delay: 5

- name: Creating Coco key exchange folder
  file:
    dest: '{{ jumpserver_path }}/coco-{{ jumpserver_version }}/data/keys'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: Coco systemd service file transfer
  template:
    src: 'coco.service.j2'
    dest: '/lib/systemd/system/coco.service'
    owner: 'root'
    group: 'root'
    mode: 0644
  register: coco_systemd_update

- name: Coco configuration file transfer
  template:
    src: 'coco_config.yml.j2'
    dest: '{{ jumpserver_path }}/coco-{{ jumpserver_version }}/config.yml'
    backup: 'yes'
    owner: 'root'
    group: 'root'
    mode: '0644'
  register: coco_conf_update
  no_log: true

- name: Enable Coco service
  systemd:
    name: 'coco.service'
    enabled: 'yes'
    state: 'restarted'
    daemon_reload: 'yes'
  when: coco_systemd_update is changed or coco_conf_update is changed
